/** Declaration file generated by dts-gen */

export function ceil10(value: any, exp: any): void;

export function floor10(value: any, exp: any): void;

export function round10(value: any, exp: any): void;

