/** Declaration file generated by dts-gen */

export function ceil10(value: number, exp: number): number;

export function floor10(value: number, exp: number): number;

export function round10(value: number, exp: number): number;

